name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
api-version: 1.18
author: ${author}
commands:
    spacecore:
        description: Base command for the plugin
        usage: /<command> <args>
        aliases: [sc]
permissions:
    spacecore.admin:
        description: Allows access to admin commands
        default: op